baseURL = ""
languageCode = "en-us"
title = "semantics etc."

[permalinks]
  post = "/:slug/"

[[menu.main]]
    url = "/"
    name = "semantics etc."
    weight = 1
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
