baseURL = ""
languageCode = "en-us"
title = "semantics etc."
theme = "hugo-xmin"

[params]
    accent = "#A31F34"

[permalinks]
  post = "/:slug/"

[[menu.main]]
    url = "/"
    name = "semantics etc."
    weight = 1